# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v4.2.0
    - name: Run install
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: build # will run `yarn build` command
    - name: Test the app
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: test # will run `yarn test` command
    - name: Generate coverage
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: coverage # will run `yarn coverage` command
    - name: Build storybook
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: build-storybook # will run `yarn build-storybook` command
    - name: Build storybook
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: build-storybook # will run `yarn build-storybook` command
    - name: Build Cypress e2e
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: e2e # will run `yarn e2e` command
    - name: Build Cypress component
      uses: borales/actions-yarn@v4
      with:
        cmd: component # will run `yarn component` command
