# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3

    - name: Install yarn
      run: npm install -g yarn      
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - name: Cache yarn dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: vivid-cache-yarn-${{ hashFiles('**/package.json') }}
    - name: Install dependencies 📦
      run: yarn install --frozen-lockfile
    
    - name: Build components
      run: yarn build
    
    - name: Unit Test components
      run: yarn test

    - name: Unit Test coverage
      run: yarn coverage

    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v4 
      with:
        build: npm run build
        start: npm start